sudo: false
language: python
services:
  - redis
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - pip install -e .
  - pip install pytest-cov
  - pip install coveralls
  #- pip install pytest  # installed by Travis by default already
script:
  - RUN_SLOW_TESTS_TOO=1 py.test --cov rq --durations=5
after_success:
  - coveralls
